### ISSUE TITLE
Mapping routes to /healthchecks-ui and showing result of network healthcheck in UI?

### ISSUE THREAD

**Issue by GurpreetSingh5** [Xabaril/AspNetCore.Diagnostics.HealthChecks#108]
Are there any samples, where the way to map all the action methods that we have in a the asp.net core app controller, as URIs to be checked during the health, is described?
And also to visually display the same on the Health Check UI.
I have swagger ( https://swagger.io/ )  implemented in the project in the controller.

Is there a way or a patch for the _/healthchecks-ui_ endpoint to pick these ?

**Comment by GurpreetSingh5** [comment]
Any update? Could you at least let know if this is achievable?

**Comment by CarlosLanderas** [comment]
Hello @GurpreetSingh5. Showing the results of swagger endpoints in the healthchecks UI would require invoking them creating random payloads for post and put requests and I can't see who would use that on a production environment. This would also collide with possible internal services validations. Maybe I am not understanding your proposal and need further information.

Talking about the TCP healthchecks, what kind of results would you like to be shown? Because the TCP healthchecks are just checking successfuls connections, no further information can be displayed.

**Comment by GurpreetSingh5** [comment]
@CarlosLanderas  - Yes. I guess you are right about the first point. This would collide with possible internal services validations. I was trying to provide health checks for just whether the routes provided by swagger are accessible or not? Kind of like a self-check.

Regarding TCP and similar health checks, I was looking into how I could use my own description to be displayed in the health check UI( in addition to the Healthcheck Status )? Also is the same possible for cloudwatch as well? Is there a service to health check cloudwatch ? or to be incorporated any time in future ?

**Comment by unaizorrilla** [comment]
Hi @GurpreetSingh5 
I'm sorry for a delay responding your questions. Cloudwatch is not as health check at this moment, but contributions are open on this project
