### ISSUE TITLE
Microsoft.AspNetCore.TestHost Startup Failure

### ISSUE THREAD

**Issue by mlapaglia** [Xabaril/AspNetCore.Diagnostics.HealthChecks#126]
When running functional tests using Microsoft's TestHost the `services.AddHealthChecksUI();` call fails with 

```
Message: System.AggregateException : One or more errors occurred. (Value cannot be null.
Parameter name: path1)
  ----> System.ArgumentNullException : Value cannot be null.
Parameter name: path1
```

I added a simple test project and ran it against `HealthChecks.UI.Sample` and used the following test

```
using HealthChecks.UI.Sample;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using NUnit.Framework;

namespace Tests
{
    public class Tests
    {
        [SetUp]
        public void Setup()
        {
        }

        [Test]
        public void Test1()
        {
            var hostBuilder = new WebHostBuilder()
                .UseStartup<Startup>();

            var testServer = new TestServer(hostBuilder);
        }
    }
}
```

Any help would be appreciated.

**Comment by theofanis** [comment]
Same error in our acceptance tests. No database name is provided in the `AddHealthChecksUI` method, so we expect the default to be created.

The error probably has to do with how the extension method is combining the path to create the file path for the sqlite db, since the content root is probably different when running the app vs running tests. Not sure but didn't do a deeper dive for now.

Check this section here: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/0e6777a3477db92d3811d3626635a60af41cc82a/src/HealthChecks.UI/ServiceCollectionExtensions.cs#L50

If you set the connection string in appsettings, you should be OK. Try the below setting in your `HealthChecks-UI` section:

`"HealthCheckDatabaseConnectionString": "Data Source=./tests-healthchecksdb"`

This works for us just fine.

FYI @mlapaglia

**Comment by mlapaglia** [comment]
Is there a way to just disable the database? I'm getting random issues with the tests failing, if I change the data source from `"Data Source=./tests-healthchecksdb"` to `"Data Source=tests-healthchecksdb"` it'll work for a while, then I'll need to add the `./` back

**Comment by unaizorrilla** [comment]
Let me check @mlapaglia, I try to respond ASAP

**Comment by auserx** [comment]
I'm having the same issue.

What's the reason of having this database parameter? Can we just disable it altogether?

**Comment by CarlosLanderas** [comment]
In Tests Assemblies **HostDefaults.ContentRootKey** is not registered in configuration providers. Please set the content root in your webhostbuilder and it should work.

```
  var hostBuilder = new WebHostBuilder()               
      .UseContentRoot(Directory.GetCurrentDirectory()) 
      .UseStartup<Startup>();                          
```

You can read more about this here:

https://github.com/aspnet/AspNetCore/issues/9675
https://github.com/aspnet/AspNetCore/issues/4206
