### ISSUE TITLE
[Q] In-memory history size

### ISSUE THREAD

**Issue by lonix1** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1291]
How many events does the in-memory history provider store - the last `n`, or all of them?

*If all - is there a way to limit the size?* (In production, I fear I will eventually use all available memory.)

Thanks!

**Comment by lonix1** [comment]
I found [this](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/tree/0931f08569685d72b985b285a4996d8326bf88df#health-status-history-timeline):
````cs
services.AddHealthChecksUI(setup =>
{
    // Set the maximum history entries by endpoint that will be served by the UI api middleware
    setup.MaximumHistoryEntriesPerEndpoint(50);
});
````

But unless I'm mistaken (?), that limits the number of events sent to the UI. It does not limit the number of events stored in the in-memory provider.

**Comment by sungam3r** [comment]
@lonix1 As I understand there is no limit on data stored in memory. This is by design. InMemory provider is suitable for testing, small projects, demos, etc. I think you may clean in-memory db manually by getting it from service provider by its name - `HealthChecksUI`.
![изображение](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/assets/21261007/c4a6e335-f8ec-4ef6-a1cc-94f1c0de96f0)
