### ISSUE TITLE
Is there a way to add HealthCheckEndpoint dynamically

### ISSUE THREAD

**Issue by C0HERENCE** [Xabaril/AspNetCore.Diagnostics.HealthChecks#1726]
I noticed that in the source code we use `IOptions<Settings>` to get Configuration.
Is there a way for us to dynamically modify some configurations in Settings, such as the the `HealthChecks` array.
Or is it possible and necessary to change  `IOptions` to `IOptionsSnapshot`

**Comment by rob-baldwin** [comment]
Hi @C0HERENCE, the only dynamic ways that I know of to configure the settings are either using [Azure App Configuration](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/doc/ui-docker.md#azure-app-configuration-service) or [Kubernetes](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/doc/k8s-ui-discovery.md).  Otherwise you're limited to either [appsettings](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#sample-2-configuration-using-appsettingsjson) or [service setup](https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks#sample-2-configuration-using-setupsettings-method)

**Comment by sungam3r** [comment]
@C0HERENCE  I think #1541 answers your question.
