### ISSUE TITLE
Identity Server URL without /

### ISSUE THREAD

**Issue by mihben** [Xabaril/AspNetCore.Diagnostics.HealthChecks#199]
If the URL of the identity server does not end with '/' the health check will be fail.

**Unhealty**:
`services.AddHealthChecks().AddIdentityServer(new Uri("http://identityserver"))`

**Healty**:
`services.AddHealthChecks().AddIdentityServer(new Uri("http://identityserver/"))`

**Comment by andresrsanchez** [comment]
Hi,

I think that it's the expected behaviour.
Source:
- https://stackoverflow.com/a/23438417
- https://stackoverflow.com/a/47019548

**Comment by CarlosLanderas** [comment]
Thanks @andresrsanchez , as you say, it seems base address needs to end with slash, and as we are using base Address in the extensions it is expected behaviour:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.IdSvr/DependencyInjection/IdSvrHealthCheckBuilderExtensions.cs#L28
