### ISSUE TITLE
MySql check no longer uses Ping

### ISSUE THREAD

**Issue by bgrainger** [Xabaril/AspNetCore.Diagnostics.HealthChecks#2031]
**What would you like to be added**:

Before https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1835, `MySqlHealthCheck` used `PingAsync` to check the server health. It now defaults to `SELECT 1;`.

I would like to be able to opt in to using a ping, or even having that restored as the default behavior.

I propose setting the default `MySqlHealthCheckOptions.CommandText` value to `null`, and having `MySqlHealthCheck` interpret that as meaning "ping the server". If `CommandText` is non-`null`, then it would be used to form a `MySqlCommand`.

**Why is this needed**:

A `COM_PING` packet will be much more lightweight to send to the server instead of executing a query, even a simple one.

**Comment by sebastienros** [comment]
There is actually another reason to restore the PING command, with [this issue](https://github.com/docker-library/mysql/issues/663)

What is happening is that the Docker image for MySql will start in a temporary state then restart in its final state. The health check based on connection string will report healthy during this pre-initialization state. the binary communication however is not enabled until the final restart is done.

In Aspire I am seeing that the functional tests are failing as they are waiting for the health checks to be successful, but then the mysql calls fail because the server restarts.

**Comment by bgrainger** [comment]
I'm not sure that using "ping" will help this scenario. If the health check that sends `COM_QUERY` with a `SELECT 1;` payload succeeds, then surely a health check that sends `COM_PING` would also succeed against the first instance of `mysqld` that's started in a `mysql` Docker container?

**Comment by bgrainger** [comment]
@sungam3r Why is this issue marked "up for grabs"? I already have a PR that will fix it: https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/2093.
