### ISSUE TITLE
[feature request] ActiveDirectory Healthcheck

### ISSUE THREAD

**Issue by amccool** [Xabaril/AspNetCore.Diagnostics.HealthChecks#439]
yeah yeah... a bit silly, but I need one.

**Comment by CarlosLanderas** [comment]
@amccool, I recommend you to create a custom healthcheck. Remember you can create healthchecks for your custom company needs and wire them with the whole ecosystem and UI. Right now, due to all the work we have to do and current Active Directory demand it is not in our roadmap.

Here you have a nice tutorial:

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/health-checks?view=aspnetcore-3.1


I hope you understand. 
Thank you very much!
