### ISSUE TITLE
Kubernetes Service Discovery

### ISSUE THREAD

**Issue by maganuk** [Xabaril/AspNetCore.Diagnostics.HealthChecks#47]
Hi, 

Thanks for the great library. If using Kubernetes Service Discovery is there any way to access the host if the health app is running on a pod in the same cluster without passing a token? Also what would be the host url in that case?

Thanks

**Comment by CarlosLanderas** [comment]
Kubernetes networking rules apply here. What are you trying to do?. Are you working with kubectl proxy or in a machine having a local k8s cluster?

**Comment by maganuk** [comment]
I've exposed the health ui through an ingress.... all our services are running on the same cluster as the health ui service. What I'd like to do is for the health ui to autodiscover these services and do health checking. For now I've created a service account with a token and it seems to be working fine. Was just wondering if there is any way to discover the services without creating the service account.

**Comment by CarlosLanderas** [comment]
You can configure the UI discovery using the default kubernetes token (described here)

https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/

The services that are being discovered successfully right now, are they configured with ClusterIP and are being discovered from the UI as a container right?

I ask because I am testing different scenarios and this helps. Thanks!

**Comment by maganuk** [comment]
@CarlosLanderas Awesome Thanks....

**Comment by CarlosLanderas** [comment]
@maganuk can we close the issue?

**Comment by maganuk** [comment]
@CarlosLanderas closing for now. Thanks
