### ISSUE TITLE
Error installing AspNetCore.HealthChecks.SendGrid

### ISSUE THREAD

**Issue by rsdelapaz** [Xabaril/AspNetCore.Diagnostics.HealthChecks#534]
Please, fill the following sections to help us fix the issue

**What happened**:

Error installing Install-Package AspNetCore.HealthChecks.SendGrid.

**What you expected to happen**:
The instalation of the package.

**How to reproduce it (as minimally and precisely as possible)**:
Install-Package AspNetCore.HealthChecks.SendGrid

**Source code sample**:

**Anything else we need to know?**:

![Error HealthCheck SendGrid](https://user-images.githubusercontent.com/36857849/82322160-59fc9d00-99d6-11ea-92f6-2e8fd0e1a909.JPG)

**Environment**:

- .NET Core version 3.1
- Healthchecks version 
- Operative system: Windows
- Others:

**Comment by CarlosLanderas** [comment]
The error you are receiving is because the package is in preview version.

Use:

`Install-Package AspNetCore.HealthChecks.SendGrid -Version 3.1.1-preview1 `

and it will work.

@unaizorrilla this package is in preview on purpose right?

**Comment by manne** [comment]
@CarlosLanderas I am the author of the `SendGrid` health check. This package is on purpose in preview. I want to use the health check in production for several weeks before "releasing" it, in order to actually test it in production. However there have been some delays using it. I will keep you informed about the progress.
If somebody says that this package is ready to release, the package can be released.
