### ISSUE TITLE
ASP.NET Core 3.1 - Health Check UI is not working.

### ISSUE THREAD

**Issue by prawin2k** [Xabaril/AspNetCore.Diagnostics.HealthChecks#540]
**What happened**:
i have developed an ASP.NET Core 3.1 MVC Application with customized Health Check. It's perfectly working fine as shown below.

![image](https://user-images.githubusercontent.com/10738750/82732217-69902480-9cfb-11ea-9e07-c403886b95da.png)

However, the UI is always empty as the /health-api always returns empty array.
![image](https://user-images.githubusercontent.com/10738750/82732257-9fcda400-9cfb-11ea-889f-986a995ff7f2.png)

![image](https://user-images.githubusercontent.com/10738750/82732269-afe58380-9cfb-11ea-937a-ffc9db1ffba2.png)

 It's in ASP.NET 3.1 Core application which can be located at https://github.com/prawin2k/HealhCheckMVC/tree/master/HealhCheckMVC

- .NET Core version - 3.1 (MVC)
- Healthchecks version - Latest
- Operative system: Windows Server 2016
- Others: Visual Studio 2019

**Comment by jreidryuzaki** [comment]
This happened to me today after adding in the 'launchUrl' to the profiles\iisexpress section in launchSettings.json.  I set it to `"launchUrl": "healthchecks-ui"`

**Comment by CarlosLanderas** [comment]
@prawin2k can you paste your whole HealthChecks configuration?
It looks like you are not specifying the endpoints to check to the UI services.

**Comment by NicolasREY69330** [comment]
@CarlosLanderas 
I have the exact same problem, but I think the problem is due to `AddHealthChecksUI()` but I can't figure out on how to use it.

I've just used the new packages for 3.1.1 version :

`    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="3.1.1" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="3.1.1" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="3.1.1" />`

Then I add a simple Postgres healthcheck in `ConfigureServices`
![image](https://user-images.githubusercontent.com/50946960/83909484-286f2a00-a769-11ea-9c89-d66e4427cddc.png)

followed by the UI part, I don't know what a I supposed to supply here ?
![image](https://user-images.githubusercontent.com/50946960/83909580-59e7f580-a769-11ea-9532-a0ae2f5155c8.png)

Then in `Configure`
![image](https://user-images.githubusercontent.com/50946960/83909647-78e68780-a769-11ea-8c06-466b88d53141.png)

The API works 
![image](https://user-images.githubusercontent.com/50946960/83909862-d7ac0100-a769-11ea-8fc1-d185ce699177.png)

But my ui keeps beeing empty... 
![image](https://user-images.githubusercontent.com/50946960/83909901-eabed100-a769-11ea-828c-ed0f24bc89ae.png)

Note : I do not use any appsettings at all, should I supply any missing data ?

**Comment by CarlosLanderas** [comment]
Yes, if you wan't the UI to check the local endpoint you should at least provide a relative endpoint to the UI settings:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.StorageProviders/Startup.cs#L38

**Comment by NicolasREY69330** [comment]
Sure it makes sense, my config should be correct now but I guess I have another hostname problem with Docker, I open a new ticket then
