### ISSUE TITLE
HealthCheck UI last execution date not picking up local time

### ISSUE THREAD

**Issue by sklawrence** [Xabaril/AspNetCore.Diagnostics.HealthChecks#55]
I can see in the code you have a function to get the locale and format the date (livenessTable.tsx:41) but it does not seem to display the correct time. It is still showing UTC time for me here in Australia.
e.g. showing
![image](https://user-images.githubusercontent.com/37350473/50732285-fcdebd80-11cb-11e9-896c-980a8672db6a.png)
You can see bottom right my local time being UTC+11.

**Comment by unaizorrilla** [comment]
Hi @sklawrence  thanks for fill the issue, let me check this!

**Comment by unaizorrilla** [comment]
Fixed on 2.0.9, at this moment is building a 2.0.9 version, please use it and close the issue if all is ok.

**Comment by rickvi1** [comment]
Hi @unaizorrilla I'm now running version 2.0.9, and there I see strange behavior in the "On state from" field. The Last Execution time is right (UTC+1), but if my app switches from healthy/unhealthy, the "On state from"field always shows "Healthy/unhealthy an hour ago). Since I'm in UTC+1, I guess this has something to do with the UTC and Non-UTC times.

![image](https://user-images.githubusercontent.com/2804958/50815293-de3c0c00-131c-11e9-9162-687ed65aa080.png)

**Comment by unaizorrilla** [comment]
My fault, let me today to fix!

**Comment by rickvi1** [comment]
Hi @unaizorrilla I've checked, it's working like a charm 👍 Thanks.

**Comment by sklawrence** [comment]
This is working for me too. Thanks for the quick response. Love your work.
