### ISSUE TITLE
Health Check 'Value cannot be null' error

### ISSUE THREAD

**Issue by sjbthfc2** [Xabaril/AspNetCore.Diagnostics.HealthChecks#634]
Hi,

I am trying to use the UI with a simple health check that returns json from an ASP.NET Core app. When I run the health check in the browser I get the following response:

`{
  "status": "Healthy"
}`

However, when running the UI, it just gets the following error:
`HealthCheck collector HostedService threw an error: Value cannot be null. (Parameter 'source')`

I use a basic ResponseWriter to write the JSON response. Am I not configuring something correctly? I originally just used the our fo the box ASP.NET Core health check but that caused a JSON parsing error as it just returns the string 'healthy'. Is a JSON response required?

Many thanks for your help

**Comment by CarlosLanderas** [comment]
The UI requires the health endpoints to use the UI response writer instead of the default one that uses text/plain response.

Take a look to the samples folder, there you can find different ways of configuration.

This could be a good start:

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/samples/HealthChecks.UI.StorageProviders/Startup.cs#L59

**Comment by sjbthfc2** [comment]
Thanks for your help, that is working correctly now.
