### ISSUE TITLE
AddSqlServerStorage: Provide possibility to pass SqlServerDbContextOptionsBuilder

### ISSUE THREAD

**Issue by VKAlwaysWin** [Xabaril/AspNetCore.Diagnostics.HealthChecks#647]
**What would you like to be added**:
Add possibility to pass SqlServerDbContextOptionsBuilder options to UseSqlServer method.

**Why is this needed**:
By default it is:
options.UseSqlServer(connectionString, s => s.MigrationsAssembly("HealthChecks.UI.SqlServer.Storage"));

And as a result it is impossible to configure SqlServer for your needs. 

Example, when no access to dbo schema it is useful to do: s.MigrationsHistoryTable

**Comment by CarlosLanderas** [comment]
Hello. Could you explain what are those needs you have with SQL Server being that the UI internally handles all the stuff?
Thanks!

**Comment by VKAlwaysWin** [comment]
@CarlosLanderas , I don't have access to dbo schema on Production Environment. Only to custom one.

**Comment by camiteca** [comment]
Hi @CarlosLanderas,

We're facing the same issue when trying to configure the DbContext on a different schema. We can't use dbo because we have another database with migrations configured in the same schema and we'd like to be able to configure the schema. We're now manually copy-pasting the content of "AddSqlServerStorage" but we find it a bit ugly.

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/d5ee46abae5b2e9c045148c677239f664052a078/src/HealthChecks.UI.SqlServer.Storage/HealthChecksUIBuilderExtensions.cs#L10

I'd gladly make a pull request with the changes if you point me out on how you want to approach this.

**Comment by CarlosLanderas** [comment]
This weekend I'm going to work on healthchecks. I'll do this :)
Thanks for your feedback!

**Comment by camiteca** [comment]
Were you able to have a look at this? If not, i can have a look at it and make a pull request.

**Comment by unaizorrilla** [comment]
PR is welcome!

**Comment by unchase** [comment]
Hi, @CarlosLanderas

Are you planning to add this feature soon?

**Comment by solutions-simplified** [comment]
@unaizorrilla were you able to get a PR submitted to allow the ability to override the default schema for the healthcheck tables?

**Comment by unaizorrilla** [comment]
I'm on the process to migrate to .NET 6 and before release these packages my idea is took all the pending PR to move also for .NET 6..

Sorry, but at this moment I'm so busy  on my work and alone maintaining different projects :-(

**Comment by sungam3r** [comment]
fixed in #1858

**Comment by sungam3r** [comment]
Will be published in v7 coming days.
