### ISSUE TITLE
URI healthcheck timeout

### ISSUE THREAD

**Issue by agcos** [Xabaril/AspNetCore.Diagnostics.HealthChecks#81]
For URI HealthChecks can I set a `Timeout`?

https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=netcore-2.2

**Comment by unaizorrilla** [comment]
related with #60 , PR is wellcome !

**Comment by wdamron** [comment]
On a related note, the `UriHealthCheck` currently ignores the passed-in `CancellationToken` when calling `var response = await httpClient.SendAsync(requestMessage);`

(see https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.Uris/UriHealthCheck.cs#L47)

**Comment by unaizorrilla** [comment]
Hi,

@wdamron already push a PR with this feature, I hope this can be merged this week.

**Comment by CarlosLanderas** [comment]
Merged in #85. Closing issue

**Comment by unaizorrilla** [comment]
Hi @agcos 
The PR from @wdamron  is merged and at this momment a new package for uri healthchecks with version 2.2.2 is building on appveyor. This package contain a timeout feature, you can check the functional tests in order to know is used
https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/test/FunctionalTests/HealthChecks.Uris/UriHealthCheckTests.cs
