### ISSUE TITLE
Add optional CosmosClientOptions to AddCosmosDb extension method

### ISSUE THREAD

**Issue by schmitzt3** [Xabaril/AspNetCore.Diagnostics.HealthChecks#828]
**What would you like to be added**:
An overload for `AddCosmosDb` that accepts an optional `CosmosClientOptions`.

**Why is this needed**:
Since the `CosmosDbHealthCheck` is newing up a `CosmosClient`, we should be able to pass options to it so that it can be configured like other instances of `CosmosClient` in an application. For example, when connecting to CosmosDB using  the Gateway `ConnectionMode`. By default, `CosmosClient` sets the the `ConnectionMode` to Direct, which isn't great for servers that only use the SQL port (443).

I have a WIP, but only have a Mac to run this code on and I wasn't exactly sure how to get it into the repo. I also added documentation and 2 tests.

https://github.com/schmitzt3/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.CosmosDb/CosmosDbHealthCheck.cs

Please let me know if I can do anything to help push this through.

Thanks!

**Comment by sungam3r** [comment]
I see a lot of `AddCosmosDb` overloads in master. Closing.

**Comment by PanosKousidis** [comment]
@sungam3r,  The available overloads use actions of `CosmosDbHealthCheckOptions` and that class does not have as many configuration properties as the `CosmosClientOptions`. For example you still cannot set the health check to use the Gateway `ConnectionMode` instead of the default Direct one. 

No further overloads are needed, but I think at least an extra property of `ConnectionMode` inside `CosmosDbHealthCheckOptions` is needed along with the respective handling of it.
